VoterRegistrationMVC/Models/VoterSearch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VoterRegistrationMVC.Models
{
    public class VoterSearch 
    { 
        public int PetitionID { get; set; } 
        public int PetitionDetailID { get; set; }
        [Key, Column(Order = 0)]
        public string MergeFileID { get; set; }
        [Key, Column(Order = 1)]
        public string VoterID { get; set; }
        public string County { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Lasst Name")]
        public string LastName { get; set; }
        [Display(Name = "House Num")]
        public string HouseNum { get; set; }
        public string StreetName { get; set; }
        public string AddressValue { get; set; }
        public int totalRows { get; set; }
        /*
        var functionId = yourIdParameter;
        var result =  db.Database.SqlQuery<GetFunctionByID>("GetFunctionByID @FunctionId", new SqlParameter("@FunctionId", functionId)).ToList());
        */
    }
}
 

VoterRegistrationMVC/Models/VoterSearchesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web; 

namespace VoterRegistrationMVC.Models
{
    public class VoterSearchesViewModel : IVoterSearchesResultsView, IVoterSearchesCriteriaView
    {


        public IEnumerable<VoterSearch> VoterSearchResults { get; set; }
        public VoterSearchCriteriaModel VoterSearchCriteriaModel { get; set; }
        
    }
}

VoterRegistrationMVC/Controllers/VoterSearchController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoterRegistrationMVC.DAL;
using VoterRegistrationMVC.Models;

namespace VoterRegistrationMVC.Controllers
{
    [RoutePrefix("VoterSearchController")]
    public class VoterSearchController : Controller
    {
        private VoterRegistrationContext db = new VoterRegistrationContext();
        

        // GET: VoterSearch
        public ActionResult Index()
        {
            return View();
        }


        //Get action for main search, intro to the whole show!
        public ActionResult Search(int PetitionID = 0, int PetitionDetailID = 0)
        {
             VoterSearchesViewModel viewModel = new VoterSearchesViewModel();
                // make sure we don't get a null reference exceptions
                viewModel.VoterSearchCriteriaModel = new VoterSearchCriteriaModel();
                viewModel.VoterSearchResults = new List<VoterSearch>();
                
                //retain the petition ID if we know it being passed thru a param, forget why now, on add I think
                if (PetitionID != 0)
                {
                    viewModel.VoterSearchCriteriaModel.PetitionID = PetitionID;
                }
                PopulatePetitionDropDownList(viewModel.VoterSearchCriteriaModel, PetitionID);
                PopulatePetitionDetailDropDownList(viewModel.VoterSearchCriteriaModel, PetitionDetailID);

            //Set Total Rows so pagination works
            ViewBag.TotalRows = viewModel.VoterSearchResults.Select(q => q.totalRows).FirstOrDefault();
            if (ViewBag.TotalRows == null)
                ViewBag.TotalRows = 0;

            //tells us which little page number to start on and highlight, annoying redundancy but another day, another time.
            ViewBag.CurrentPage = 1;
            viewModel.VoterSearchCriteriaModel.Page = 1;

            return this.View(viewModel);

            
                
        }

        //comes here after entering found voter
        [Route("SearchAfterFound")]
        public ActionResult SearchAfterFound(int PetitionID = 0, int PetitionDetailID = 0)
        {
            VoterSearchesViewModel viewModel = new VoterSearchesViewModel();
            // make sure we don't get a null reference exceptions
            viewModel.VoterSearchCriteriaModel = new VoterSearchCriteriaModel();
            viewModel.VoterSearchResults = new List<VoterSearch>();

            PopulatePetitionDropDownList(viewModel.VoterSearchCriteriaModel, PetitionID);
            PopulatePetitionDetailDropDownList(viewModel.VoterSearchCriteriaModel, PetitionDetailID);
            return View("~/Views/VoterSearch/Search.cshtml");
        }


        [HttpPost]
        public ActionResult PetitionChange(int PetitionID = 0)
        {
            VoterSearchesViewModel viewModel = new VoterSearchesViewModel();
            // make sure we don't get a null reference exceptions
            viewModel.VoterSearchCriteriaModel = new VoterSearchCriteriaModel();
            if (PetitionID != 0)
            {
                viewModel.VoterSearchCriteriaModel.PetitionID = PetitionID;
            }
            
            PopulatePetitionDetailDropDownList(viewModel.VoterSearchCriteriaModel, 0);
            
            return Json(viewModel.VoterSearchCriteriaModel.PetitionDetailValues);

        }


        //After we submit the form, or if we click on a pagination button -- javascript switches it from get to post.
        [HttpPost]
        public ActionResult Search(VoterSearchesViewModel model)
        {
            int page = 0;
            page = model.VoterSearchCriteriaModel.Page ?? 0;



            model.VoterSearchResults = GetVoterResults(model.VoterSearchCriteriaModel, page);
            PopulatePetitionDropDownList(model.VoterSearchCriteriaModel, 0);
            PopulatePetitionDetailDropDownList(model.VoterSearchCriteriaModel, 0);
             

            ViewBag.TotalRows = model.VoterSearchResults.Select(q => q.totalRows).FirstOrDefault();
            if (ViewBag.TotalRows == null)
                ViewBag.TotalRows = 0;

            ViewBag.CurrentPage = page;

            return View(model);
        }


        [Route("AddVoter")]
        public ActionResult AddVoter(string VoterID, int PetitionID, int PetitionDetailID)
        {
           
            string query = "EXEC dbo.sp_VoterPetitionAdd @VoterID, @PetitionID, @PetitionDetailID";
            SqlParameter petitionIDParam = new SqlParameter("PetitionID", PetitionID);
            SqlParameter PetitionDetailIDParam = new SqlParameter("PetitionDetailID", PetitionDetailID);
            SqlParameter VoterIDParam = new SqlParameter("VoterID", VoterID); 

            //add the voter
            db.Database.ExecuteSqlCommand(query, VoterIDParam, petitionIDParam, PetitionDetailIDParam);

            string var = Request.UrlReferrer.ToString();
            //return Redirect(Request.UrlReferrer.ToString());
            return RedirectToAction("Search", new { PetitionID = PetitionID, PetitionDetailID = PetitionDetailID });
        }


        private void PopulatePetitionDropDownList(VoterSearchCriteriaModel criteria, int SelectedValue)
        {

            criteria.Petitions = 
            db.Petitions.Select(h => 
                                new SelectListItem
                                { Text = h.PetitionName, Value = h.PetitionID.ToString() }
                               ).ToList();

            if (SelectedValue != 0)
            {
                SelectListItem selected = criteria.Petitions.FirstOrDefault(x => x.Value.Equals(SelectedValue));
                if (selected != null)
                {
                    criteria.Petitions = new SelectList(criteria.Petitions, "value", "text", selected.Value);
                } 
            } 

        }

        private void PopulatePetitionDetailDropDownList(VoterSearchCriteriaModel criteria, int SelectedValue)
        {
            int _PetitionID = criteria.PetitionID;
            if (_PetitionID == 0)
            {
                _PetitionID = 1;
            }



            if (SelectedValue != 0)
            {
                criteria.PetitionDetailValues =
                db.PetitionDetails.Where(X => X.PetitionID == _PetitionID).Select(h =>
                                new SelectListItem
                                { Text = h.PetitionDetailID.ToString() + "-" + h.PersonAssigned, Value = h.PetitionDetailID.ToString(), Selected = h.PetitionDetailID.Equals(SelectedValue) }
                               ).ToList();
                criteria.PetitionDetailID = SelectedValue;
            }
            else
            {
                criteria.PetitionDetailValues =
                    db.PetitionDetails.Where(X => X.PetitionID == _PetitionID).Select(h =>
                                new SelectListItem
                                { Text = h.PetitionDetailID.ToString() + "-" + h.PersonAssigned, Value = h.PetitionDetailID.ToString() }
                               ).ToList();
            }
        }


        private IEnumerable<VoterSearch> GetVoterResults(VoterSearchCriteriaModel criteria, int page)
        {

            int PetitionID = criteria.PetitionID;
            int PeitionDetailID = criteria.PetitionDetailID;
            int startNum = (page * 25)+1;
            int endNum = startNum + (25-1);
            criteria.Page = 1;

            String FirstName = String.Empty;
            if (criteria.FirstName != null)
                FirstName = criteria.FirstName;
            else
            {
                FirstName = String.Empty;
            }

            String LastName = String.Empty;
            if (criteria.LastName != null)
                LastName = criteria.LastName;
            else
            {
                LastName = String.Empty;
            }

            String HouseNum = String.Empty;
            if (criteria.HouseNumber != null)
                HouseNum = criteria.HouseNumber;
            else
            {
                HouseNum = String.Empty;
            }
             

            string query = "EXEC dbo.sp_VoterSearch @PetitionID, @PetitionDetailID, @FirstName, @LastName, @HouseNum, @startNum, @endNum";
            SqlParameter petitionIDParam = new SqlParameter("PetitionID", PetitionID);
            SqlParameter PetitionDetailIDParam = new SqlParameter("PetitionDetailID", PeitionDetailID);
            SqlParameter FirstNameParam = new SqlParameter("FirstName", FirstName);
            SqlParameter LastNameParam = new SqlParameter("LastName", LastName);
            SqlParameter HouseNumParam = new SqlParameter("HouseNum", HouseNum);
            SqlParameter startNumParam = new SqlParameter("startNum", startNum);
            SqlParameter endNumParam = new SqlParameter("endNum", endNum);


            IEnumerable<VoterSearch> data = db.Database.SqlQuery<VoterSearch>(query, petitionIDParam, PetitionDetailIDParam, FirstNameParam, LastNameParam, HouseNumParam, startNumParam, endNumParam).ToList();

            //we dont get all the rows, we just get what we need and let the query tell us how many total if we were to get all of them
            //less data less overhead
            if (data.Count() != 0)
            { 
                ViewBag.TotalRows = data.Select(x => x.totalRows).First();
            }


            if (ViewBag.TotalRows == null)
            {
                ViewBag.TotalRows = 0;
            }

            return data;


        }


    }
}

VoterRegistrationMVC/Controllers/VoterSearchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VoterRegistrationMVC.DAL;
using VoterRegistrationMVC.Models;

namespace VoterRegistrationMVC.Controllers
{
    public class VoterSearchesController : Controller
    {
        private VoterRegistrationContext db = new VoterRegistrationContext();

        // GET: VoterSearches
        public ActionResult Index()
        {
            PopulatePetitionDropDownList();
            string query = "EXEC sp_VoterSearch 0,0,'','',''";
            IEnumerable<VoterSearch> data = db.Database.SqlQuery<VoterSearch>(query);
            //var data = db.sp_VoterSearch(1).ToList(); // db.VoterSearch.ToList();
            return View(data.ToList());

            //return View(db.VoterSearch.ToList());
        }
         

        [HttpGet]
        public ActionResult WebGrid()
        {
            PopulatePetitionDropDownList();
            string query = "EXEC sp_VoterSearch 0,0,'','',''";
            IEnumerable<VoterSearch> data = db.Database.SqlQuery<VoterSearch>(query);
            //var data = db.sp_VoterSearch(1).ToList(); // db.VoterSearch.ToList();
            return View(data.ToList());
        }

   

        [HttpPost]
        public ActionResult WebGrid(FormCollection form)
        {
            PopulatePetitionDropDownList();

           //String PetitionID =  form["PetitionID"].ToString();

            int PetitionID = Convert.ToInt32(Request.Form["PetitionID"].ToString());
            int PeitionDetailID = 1;
            String FirstName = Request.Form["FirstName"].ToString();
            String LastName = Request.Form["LastName"].ToString();
            String HouseNum = Request.Form["HouseNumber"].ToString();

            
            string query = "EXEC dbo.sp_VoterSearch @PetitionID, @PetitionDetailID, @FirstName, @LastName, @HouseNum";
            SqlParameter petitionIDParam = new SqlParameter("PetitionID", PetitionID);
            SqlParameter PetitionDetailIDParam = new SqlParameter("PetitionDetailID", PeitionDetailID);
            SqlParameter FirstNameParam = new SqlParameter("FirstName", FirstName);
            SqlParameter LastNameParam = new SqlParameter("LastName", LastName);
            SqlParameter HouseNumParam = new SqlParameter("HouseNum", HouseNum);


            IEnumerable<VoterSearch> data = db.Database.SqlQuery<VoterSearch>(query, petitionIDParam, PetitionDetailIDParam, FirstNameParam, LastNameParam, HouseNumParam);
            //var data = db.sp_VoterSearch(1).ToList(); // db.VoterSearch.ToList();
            return View(data.ToList());
        }


        private void PopulatePetitionDropDownList(object selectedPetition = null)
        {
            var petitionQuery = from d in db.Petitions 
                             orderby d.PetitionName
                             select d;

            ViewBag.PetitionID = new SelectList(petitionQuery, "PetitionID", "PetitionName", selectedPetition);
        }

        /*
        private void PopulatePetitionDetailDropDownList(object selectPetitionDetail = null)
        {
            var petitionDetailQuery = from d in db.Petitions
                                orderby d.PetitionName
                                select d;

            ViewBag.PetitionID = new SelectList(petitionQuery, "PetitionID", "PetitionName", selectedTeams);
        }*/

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VoterRegistrationMVC/Views/VoterSearches/Create.cshtml
@model VoterRegistrationMVC.Models.VoterSearch

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VoterSearch</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MergeFileID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MergeFileID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MergeFileID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VoterID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VoterID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VoterID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetitionID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetitionID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetitionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetitionDetailID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PetitionDetailID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetitionDetailID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.County, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.County, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.County, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HouseNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StreetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VoterRegistrationMVC/Views/VoterSearches/Delete.cshtml
@model VoterRegistrationMVC.Models.VoterSearch

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>VoterSearch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PetitionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetitionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetitionDetailID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetitionDetailID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HouseNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HouseNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressValue)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VoterRegistrationMVC/Views/VoterSearches/Details.cshtml
@model VoterRegistrationMVC.Models.VoterSearch

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VoterSearch</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PetitionID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetitionID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetitionDetailID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetitionDetailID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HouseNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HouseNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StreetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressValue)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VoterRegistrationMVC/Views/VoterSearches/Index.cshtml
@model IEnumerable<VoterRegistrationMVC.Models.VoterSearch>

@{
    ViewBag.Title = "WebGrid";
}

<h2>Index</h2>

@* Html.BeginForm is used to add a form in an Html document *@
@* Pass the action name in the first parameter, controller name in the second parameter and specify the form request type as get *@

@using (Html.BeginForm("Index", "VoterSearches", FormMethod.Get))
{
    //the following are search options
    <b> Search Option: </b>
    @Html.Label("First Name:")
    @Html.TextBox("FirstName", null, new { @class = "form-control" })
}

<div id="DivGrid">
    @{

        WebGrid grid = new WebGrid(Model, rowsPerPage: 25, columnNames: new[] { "VoterID", "FirstName", "LastName", "HouseNum", "StreetName", "AddressValue" });

       
    }

    @grid.GetHtml(columns: grid.Columns(
                                        grid.Column("FirstName", header: "First Name"),
                                        grid.Column("LastName", "Last Name"),
                                        grid.Column("HouseNum", "House Number"),
                                        grid.Column("StreetName", "Street Name")
                                        )
                 )
</div>





@*
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PetitionID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PetitionDetailID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.County)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HouseNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StreetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AddressValue)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PetitionID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PetitionDetailID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.County)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HouseNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StreetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddressValue)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

    </table>
*@

VoterRegistrationMVC/Views/VoterSearches/WebGrid.cshtml
@model IEnumerable<VoterRegistrationMVC.Models.VoterSearch>

@{
    ViewBag.Title = "WebGrid";
}

@* Html.BeginForm is used to add a form in an Html document *@
@* Pass the action name in the first parameter, controller name in the second parameter and specify the form request type as get *@
<h1>Find Registered Voters</h1>

<div id ="SearchBox"class="editor">
    @using (Html.BeginForm("WebGrid", "VoterSearches"))
    {
        @Html.Label("Select Petition:")
        /*@Html.DropDownList("PetitionID", new List<SelectListItem>(), new { @class = "form-control" })*/
         @Html.DropDownList("PetitionID", null, "", new { @class = "form-control", required = "required" })

        //the following are search options
        @Html.Label("First Name:")
        @Html.TextBox("FirstName", null, new { @class = "form-control" })

        @Html.Label("Last Name:")
        @Html.TextBox("LastName", null, new { @class = "form-control" })

        @Html.Label("House Number:")
        @Html.TextBox("HouseNumber", null, new { @class = "form-control" })

        <input type="submit" value="Search" /> 
    }
</div>

<br />



<div id="DivGrid" class="gTable">
    @{

        WebGrid grid = new WebGrid(Model, rowsPerPage: 25, canPage: false, columnNames: new[] { "VoterID", "FirstName", "LastName", "HouseNum", "StreetName", "AddressValue" }, selectionFieldName: "VoterID" );


    }

    @grid.GetHtml(columns: grid.Columns(
                                        grid.Column("VoterID", header: "Voter ID", format: (item) => item.GetSelectLink(item.VoterID.ToString())),
                                        grid.Column("FirstName", header: "First Name"),
                                        grid.Column("LastName", "Last Name"),
                                        grid.Column("HouseNum", "House Number"),
                                        grid.Column("StreetName", "Street Name")
                                        ),
                          tableStyle: "gTable",
                          selectedRowStyle: "selectedRow"
                 )
</div>
 