VoterRegistrationMVC/Models/PetitionSignatureSearch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace VoterRegistrationMVC.Models
{
    public class PetitionSignatureSearch
    {

        public int PetitionID { get; set; }

        public int PetitionDetailID { get; set; }

        [Key, Column(Order = 0)]
        public string MergeFileID { get; set; }

        [Key, Column(Order = 1)]
        public string VoterID { get; set; }

        public string County { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Lasst Name")]
        public string LastName { get; set; }

        [Display(Name = "House Num")]
        public string HouseNum { get; set; }

        public string StreetName { get; set; }

        public string AddressValue { get; set; } 

        public int totalRows { get; set; }
    }
}

VoterRegistrationMVC/Controllers/PetitionSignatureSearchController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoterRegistrationMVC.DAL;
using VoterRegistrationMVC.Models;

namespace VoterRegistrationMVC.Controllers
{
    [RoutePrefix("PetitionSignatureController")]
    public class PetitionSignatureSearchController : Controller
    {

        private VoterRegistrationContext db = new VoterRegistrationContext();

        // GET: PetitionSignatureSearch
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search(int PetitionID = 0, int PetitionDetailID = 0)
        {
           PetitionSignaturesSearchViewModel viewModel = new PetitionSignaturesSearchViewModel();
            // make sure we don't get a null reference exceptions
            viewModel.PetitionSignatureSearchCriteriaModel = new PetitionSignatureSearchCriteriaModel();
            viewModel.PetitionSignatureSearchResults = new List<PetitionSignatureSearch>();

            //retain the petition ID if we know it being passed thru a param, forget why now, on add I think
            if (PetitionID != 0)
            {
                viewModel.PetitionSignatureSearchCriteriaModel.PetitionID = PetitionID;
            }
            PopulatePetitionDropDownList(viewModel.PetitionSignatureSearchCriteriaModel, PetitionID);
            PopulatePetitionDetailDropDownList(viewModel.PetitionSignatureSearchCriteriaModel, PetitionDetailID);

            //Set Total Rows so pagination works
            ViewBag.TotalRows = viewModel.PetitionSignatureSearchResults.Select(q => q.totalRows).FirstOrDefault();
            if (ViewBag.TotalRows == null)
                ViewBag.TotalRows = 0;

            //tells us which little page number to start on and highlight, annoying redundancy but another day, another time.
            ViewBag.CurrentPage = 1;
            viewModel.PetitionSignatureSearchCriteriaModel.Page = 1;

            return this.View(viewModel);
        }

        [HttpPost]
        public ActionResult Search(PetitionSignaturesSearchViewModel model)
        {
            int page = 0;
            page = model.PetitionSignatureSearchCriteriaModel.Page ?? 0;



            model.PetitionSignatureSearchResults = GetVoterResults(model.PetitionSignatureSearchCriteriaModel, page);
            PopulatePetitionDropDownList(model.PetitionSignatureSearchCriteriaModel, 0);
            PopulatePetitionDetailDropDownList(model.PetitionSignatureSearchCriteriaModel, 0);


            ViewBag.TotalRows = model.PetitionSignatureSearchResults.Select(q => q.totalRows).FirstOrDefault();
            if (ViewBag.TotalRows == null)
                ViewBag.TotalRows = 0;

            ViewBag.CurrentPage = page;

            return View(model);
        }


        [Route("RemoveVoter")]
        public ActionResult RemoveVoter(string VoterID, int PetitionID, int PetitionDetailID)
        {

            string query = "EXEC dbo.sp_VoterPetitionRemove @VoterID, @PetitionID, @PetitionDetailID";
            SqlParameter petitionIDParam = new SqlParameter("PetitionID", PetitionID);
            SqlParameter PetitionDetailIDParam = new SqlParameter("PetitionDetailID", PetitionDetailID);
            SqlParameter VoterIDParam = new SqlParameter("VoterID", VoterID);

            //add the voter
            db.Database.ExecuteSqlCommand(query, VoterIDParam, petitionIDParam, PetitionDetailIDParam);

            string var = Request.UrlReferrer.ToString();
            //return Redirect(Request.UrlReferrer.ToString());
            return RedirectToAction("Search", new { PetitionID = PetitionID, PetitionDetailID = PetitionDetailID });
        }






        private void PopulatePetitionDropDownList(PetitionSignatureSearchCriteriaModel criteria, int SelectedValue)
        {

            criteria.Petitions =
            db.Petitions.Select(h =>
                                new SelectListItem
                                { Text = h.PetitionName, Value = h.PetitionID.ToString() }
                               ).ToList();

            if (SelectedValue != 0)
            {
                SelectListItem selected = criteria.Petitions.FirstOrDefault(x => x.Value.Equals(SelectedValue));
                if (selected != null)
                {
                    criteria.Petitions = new SelectList(criteria.Petitions, "value", "text", selected.Value);
                }
            }
            //SelectList myList = GetMySelectList();
            //SelectListItem selected = myList.FirstOrDefault(x => x.Text.ToUpper().Contains("UNITED STATES"));
            //if (selected != null)
            //{
            //    myList = new SelectList(myList, "value", "text", selected.Value);
            //}

        }

        [HttpPost]
        public ActionResult PetitionChange(int PetitionID = 0)
        {
            PetitionSignaturesSearchViewModel viewModel = new PetitionSignaturesSearchViewModel();
            // make sure we don't get a null reference exceptions
            viewModel.PetitionSignatureSearchCriteriaModel = new PetitionSignatureSearchCriteriaModel();
            if (PetitionID != 0)
            {
                viewModel.PetitionSignatureSearchCriteriaModel.PetitionID = PetitionID;
            }

            PopulatePetitionDetailDropDownList(viewModel.PetitionSignatureSearchCriteriaModel, 0);

            return Json(viewModel.PetitionSignatureSearchCriteriaModel.PetitionDetailValues);

        }



        private void PopulatePetitionDetailDropDownList(PetitionSignatureSearchCriteriaModel criteria, int SelectedValue)
        {
            int _PetitionID = criteria.PetitionID;
            if (_PetitionID == 0)
            {
                _PetitionID = 1;
            }



            if (SelectedValue != 0)
            {
                criteria.PetitionDetailValues =
                db.PetitionDetails.Where(X => X.PetitionID == _PetitionID).Select(h =>
                                new SelectListItem
                                { Text = h.PetitionDetailID.ToString() + "-" + h.PersonAssigned, Value = h.PetitionDetailID.ToString(), Selected = h.PetitionDetailID.Equals(SelectedValue) }
                               ).ToList();
                criteria.PetitionDetailID = SelectedValue;
            }
            else
            {
                criteria.PetitionDetailValues =
                    db.PetitionDetails.Where(X => X.PetitionID == _PetitionID).Select(h =>
                                new SelectListItem
                                { Text = h.PetitionDetailID.ToString() + "-" + h.PersonAssigned, Value = h.PetitionDetailID.ToString() }
                               ).ToList();
            }
        }


        private IEnumerable<PetitionSignatureSearch> GetVoterResults(PetitionSignatureSearchCriteriaModel criteria, int page)
        {

            int PetitionID = criteria.PetitionID;
            int PeitionDetailID = criteria.PetitionDetailID;
            int startNum = (page * 25) + 1;
            int endNum = startNum + (25 - 1);
            criteria.Page = 1;

            String FirstName = String.Empty;
            if (criteria.FirstName != null)
                FirstName = criteria.FirstName;
            else
            {
                FirstName = String.Empty;
            }

            String LastName = String.Empty;
            if (criteria.LastName != null)
                LastName = criteria.LastName;
            else
            {
                LastName = String.Empty;
            }

            String HouseNum = String.Empty;
            if (criteria.HouseNumber != null)
                HouseNum = criteria.HouseNumber;
            else
            {
                HouseNum = String.Empty;
            }


            string query = "EXEC dbo.[sp_ReturnAssignedVoters] @PetitionID, @PetitionDetailID, @FirstName, @LastName, @HouseNum";
            SqlParameter petitionIDParam = new SqlParameter("PetitionID", PetitionID);
            SqlParameter PetitionDetailIDParam = new SqlParameter("PetitionDetailID", PeitionDetailID);
            SqlParameter FirstNameParam = new SqlParameter("FirstName", FirstName);
            SqlParameter LastNameParam = new SqlParameter("LastName", LastName);
            SqlParameter HouseNumParam = new SqlParameter("HouseNum", HouseNum);
            SqlParameter startNumParam = new SqlParameter("startNum", startNum);
            SqlParameter endNumParam = new SqlParameter("endNum", endNum);


            IEnumerable<PetitionSignatureSearch> data = db.Database.SqlQuery<PetitionSignatureSearch>(query, petitionIDParam, PetitionDetailIDParam, FirstNameParam, LastNameParam, HouseNumParam, startNumParam, endNumParam).ToList();

            //we dont get all the rows, we just get what we need and let the query tell us how many total if we were to get all of them
            //less data less overhead
            if (data.Count() != 0)
            {
                ViewBag.TotalRows = data.Select(x => x.totalRows).First();
            }


            if (ViewBag.TotalRows == null)
            {
                ViewBag.TotalRows = 0;
            }

            return data;


        }

    }
}

VoterRegistrationMVC/Views/PetitionSignatureSearch/PeitionSignatureSearchResults.cshtml
@model VoterRegistrationMVC.Models.IPetitionSignatureSearchResultsView




<div id="DivGrid" class="gTable">
    @{


        WebGrid grid = new WebGrid(rowsPerPage: 25, canPage: false, columnNames: new[] { "VoterID", "FirstName", "LastName", "HouseNum", "StreetName", "AddressValue", "Remove" }, selectionFieldName: "Remove");
        grid.Bind(source: Model.PetitionSignatureSearchResults, autoSortAndPage: false, rowCount: ViewBag.TotalRows);

    }

    @grid.GetHtml(
                    columns: grid.Columns(
                                        grid.Column("VoterID", header: "Voter ID"), //, format: (item) => Html.ActionLink("Add Voter", "AddVoter", "VoterSearch", new { VoterID = (String)item.VoterID, PetitionID = (int)item.PetitionID, PetitionDetailID = (int)item.PetitionDetailID }, null)),
                                        grid.Column("FirstName", header: "First Name"),
                                        grid.Column("LastName", header: "Last Name"),
                                        grid.Column("HouseNum", header: "House Number"),
                                        grid.Column("StreetName", header: "Street Name"),
                                        grid.Column("Remove", header: "Remove", format: (item) => Html.ActionLink("Remove Voter", "RemoveVoter", "PetitionSignatureSearch", new { VoterID = (String)item.VoterID, PetitionID = (int)item.PetitionID, PetitionDetailID = (int)item.PetitionDetailID }, null))
                                        ),
                          tableStyle: "gTable",
                          selectedRowStyle: "selectedRow",
                          // footerStyle: "webgrid-footer",
                          //  mode : WebGridPagerModes.Numeric,
                          htmlAttributes: new { id = "tblPetitionSearchResults" }
                 )

    <div class="container-fluid pagination-lg">
        <ul id="PagingFooter" class="pagination pagination-lg">
            @{
                var totalPages = (int)Math.Ceiling((double)ViewBag.TotalRows / 25) - 1;
                var PageLink = "PageLink";

                for (var i = 1; i <= totalPages; i++)
                {
                    PageLink = "PageLink" + i;

                    if (ViewBag.CurrentPage == i)
                    {
                        <li class="active">
                            <a id="@PageLink" href="/VoterSearch/Search?page=@i">@i</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a id="@PageLink" href="/VoterSearch/Search?page=@i">@i</a>
                        </li>
                    }


                }




            }
        </ul>
    </div>
</div>

<script>


    $('#PagingFooter a').click(function () {
        // when the user clicks on any of the pager links
        // try to extract the page number from the link and
        // set the value of the hidden field
        var page = this.href.match(/page=([0-9])+/)[1];

        $('#page').val(page);


        // submit the form so that the POST action is invoked
        // passing along the search criteria along
        // with the page hidden field value to the Index action
        $('form').submit();

        // cancel the default action of the link which is to simply redirect
        // to the Index action using a GET verb.
        return false;
            }
         )


</script>

</div>

VoterRegistrationMVC/Views/PetitionSignatureSearch/PetitionSignatureSearchCriteria.cshtml
@model VoterRegistrationMVC.Models.IPetitionSignatureSearchCriteriaView


 
<div id="SearchBox" class="editor">
    @using (Html.BeginForm(new { id = "searchCriteria" }))
    {
        // Here is were the magic is, if you use the @Html.*For(m=>)
        // Methods, they will create names that match the model
        // and you can back back to the same model on Get/Post

        /*@Html.DropDownList("PetitionID", new List<SelectListItem>(), new { @class = "form-control" })
        @Html.DropDownList("PetitionID", null, "", new { @class = "form-control", required = "required" })*/

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(m => m.PetitionSignatureSearchCriteriaModel.Petitions, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.PetitionSignatureSearchCriteriaModel.PetitionID, Model.PetitionSignatureSearchCriteriaModel.Petitions, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.PetitionSignatureSearchCriteriaModel.PetitionID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
                    @Html.Label("First Name:", null, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.PetitionSignatureSearchCriteriaModel.FirstName, null, new { @class = "form-control" })
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group">
                    @Html.Label("Last Name:", null, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.PetitionSignatureSearchCriteriaModel.LastName, null, new { @class = "form-control" })
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group"> 
                    <div class="col-md-10">
                        <input type="submit" value="Search" onclick="DoSubmit()" />
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="col-md-6">
                <div class="form-group" style="white-space:nowrap">
                    @Html.LabelFor(m => m.PetitionSignatureSearchCriteriaModel.PetitionDetailValues, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10" style="white-space:nowrap">
                        @Html.DropDownListFor(m => m.PetitionSignatureSearchCriteriaModel.PetitionDetailID, Model.PetitionSignatureSearchCriteriaModel.PetitionDetailValues, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.PetitionSignatureSearchCriteriaModel.PetitionDetailID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="form-group" style="white-space:nowrap">
                    @Html.Label("House Number:", null, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => Model.PetitionSignatureSearchCriteriaModel.HouseNumber, null, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
  

        @Html.HiddenFor(x => x.PetitionSignatureSearchCriteriaModel.Page, new { id = "page" })

    }
</div>


<script>
    function DoSubmit() {
        //If we reclick the search button it makes sense to send us back to page 1
        document.getElementById("page").value = "1";

        document.getElementById("frmCriteria").submit();
    }
</script>

VoterRegistrationMVC/Views/PetitionSignatureSearch/Search.cshtml
@model VoterRegistrationMVC.Models.PetitionSignaturesSearchViewModel


@section scripts
{
    <script language="javascript" type="text/javascript">
        $(document).on('change', '#PetitionSignatureSearchCriteriaModel_PetitionID', function () {

            var value = $('#PetitionSignatureSearchCriteriaModel_PetitionID').val();
            //alert(value);
            var url = "/PetitionSignatureSearch/PetitionChange/";

            //this fills our detail petition id drop down
            $.ajax({
                url: url,
                data: { PetitionID: value },
                cache: false,
                type: "POST",
                success: function (data) {
                    var markup;
                    if (data.length == 0)
                    {
                        markup = "<option value='0'>Select Detail Petition ID</option>";
                    }

                    for (var x = 0; x < data.length; x++) {
                        markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                    }
                    $("#PetitionSignatureSearchCriteriaModel_PetitionDetailID").html(markup).show();
                },
                error: function (reponse) {
                    alert("error : " + reponse);
                }


            })
        })


    </script>
}




@Html.Partial("PetitionSignatureSearchCriteria", Model)

<div id="searchResults">
    @Html.Partial("PeitionSignatureSearchResults", Model)
</div>
 